server:
  port: 8080
cors:
  originPatterns: https://certa.com.br,http://localhost:8080,http://localhost:3000
file:
  upload-dir: C:\Users\ian.silva\OneDrive - Certacon\Documentos\UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_certacon
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    org.springframework.web: DEBUG
springdoc:
  pathsToMatch:
    - /**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true