name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Build Application with Maven
      run: mvn clean package

    - name: Build Docker Image with Docker Compose
      run: docker-compose build

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag cursoRest:latest ${{ secrets.DOCKER_USERNAME }}/cursoRest:latest
        docker tag cursoRest:latest ${{ secrets.DOCKER_USERNAME }}/cursoRest:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/cursoRest:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/cursoRest:${{ github.run_id }}
        
